### PR TITLE
Add support for --bqStreamingDocTypes=*

### PR DESCRIPTION
**Pull request by relud**
cc @whd

### CODE REVIEW

**Comment by relud** [comment]
@whd I'd like to request that all the bq sink jobs spend a full UTC day in nonprod with `--bqStreamingDocTypes=*` and with `--diskSizeGb` and `--workerDiskType` set the same as on the decoder, so that we can get an accurate cost estimate

**Comment by whd** [comment]
> @whd I'd like to request that all the bq sink jobs spend a full UTC day in nonprod with `--bqStreamingDocTypes=*` and with `--diskSizeGb` and `--workerDiskType` set the same as on the decoder, so that we can get an accurate cost estimate for comparison

Ok, some of that is configured [here](https://github.com/mozilla/gcp-ingestion/blob/master/ingestion-beam/bin/build-template) and some [here](https://github.com/mozilla-services/cloudops-infra/blob/master/projects/beam/Jenkinsfile.build#L83). It's probably best to:

1. Put the parameters changes for the bq sink template build in a branch in this repo
2. Put the `bqStreamingDocTypes=*` change in a branch in the infra repo
3. Run the template build job and deploy jobs referencing those branches for nonprod

Likely we should aim for UTC Friday to be the full day (i.e. roll this out tomorrow).

**Comment by relud** [comment]
1. okay, named it `deploy-all-streaming`
2. https://github.com/mozilla-services/cloudops-infra/pull/1261
3. waiting until tomorrow

**Comment by jklukas** [comment]
> Likely we should aim for UTC Friday to be the full day (i.e. roll this out tomorrow).

I don't think we need to use midnight as the cutoff. If we get this deployed relatively early in the day today, we can choose any hour after it gets caught up as the start of the validation window.

**Comment by relud** [comment]
> I don't think we need to use midnight as the cutoff.

I expect the gcp billing dashboard to be giving me UTC days, but i'll double-check

**Comment by relud** [comment]
https://cloud.google.com/billing/docs/how-to/reports

> Time periods in the billing report use the Pacific Time Zone, and observe daylight saving time shifts.

apparently I need a PDT day

**Comment by whd** [comment]
Welp, I guess the 9th PDT will be the day. I can start this on the earlier side anyway if desired so we can debug any issues.

**Pull request merged**
