### PR TITLE
beam 2.31 -> 2.32

### PR DESCRIPTION
**Pull request by jklukas**

### CODE REVIEW

**Comment by jklukas** [comment]
Looks like there's a hadoop dep mismatch:

```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.NoSuchMethodError: 'void com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.<init>(com.google.cloud.hadoop.gcsio.GoogleCloudStorageOptions, com.google.api.services.storage.Storage, com.google.auth.Credentials)'
	at com.mozilla.telemetry.integration.BigQueryIntegrationTest.canWriteViaFileLoads(BigQueryIntegrationTest.java:182)
Caused by: java.lang.NoSuchMethodError: 'void com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.<init>(com.google.cloud.hadoop.gcsio.GoogleCloudStorageOptions, com.google.api.services.storage.Storage, com.google.auth.Credentials)'
```

**Comment by jklukas** [comment]
See https://beam.apache.org/get-started/downloads/#2320-2021-08-11 for release notes

**Review by relud — APPROVED** [review]
r+ with passing CI

**Comment by relud** [comment]
> Looks like there's a hadoop dep mismatch

the pubsub-lite dep is pulling in an older version of `com.google.cloud.bigdataoss:gcsio` that lacks a new constructor

**Comment by jklukas** [comment]
Thank you, @relud!

**Pull request merged**
