### PR TITLE
Remove fixed list of query params for impression aggregation

### PR DESCRIPTION
**Pull request by BenWu**
This should fix it but this seems like this can easily happen again and it might be tricky to catch in unit tests.  I think the aggregation fields was used to reduce the number of keys to group by but I'm not sure if it's useful.  I can look at the query params that we're actually receiving and see if this is needed.

### CODE REVIEW

**Comment by BenWu** [comment]
I didn't find any impressions urls that have unexpected query params so having an allow list of params shouldn't be needed.

Redash isn't working for me right now but this is the query I used to check:
```
SELECT
  REGEXP_EXTRACT_ALL(reporting_url, '[\\?&]([^=]+=[^&]*)') AS query_params,
  reporting_url,
FROM
  `moz-fx-data-shared-prod.contextual_services_stable.topsites_impression_v1`
WHERE
  DATE(submission_timestamp) = "2021-08-18"
ORDER BY
  ARRAY_LENGTH(query_params) DESC
```

**Review by jklukas — APPROVED** [review]
Removing the list of allowed fields seems reasonable. I think the headache of forgetting to add future fields to the list is probably greater than the risk of an unexpected param showing up here.

**Comment by BenWu** [comment]
Repurposed this pr to remove the fixed list so requesting re-review

**Review by jklukas — APPROVED** [review]
Looks great 👍

**Pull request merged**
