### PR TITLE
chore(doc): Update ingestion diagram.

### PR DESCRIPTION
**Pull request by mikaeld**
# Description

[Lucidchart editable link](https://lucid.app/lucidchart/ea46146e-fbfd-4830-87e2-ac55b6f4b0cb/edit?invitationId=inv_011b7ef4-9253-413f-8489-ceacb5830d83) added in SVG file as comment. Requires a Lucidchart licence registered with a mozilla.com account.

Replace outdated GCP-ingestion architecture diagram.

### CODE REVIEW

**Review by relud — COMMENTED** [review]
I think the decoded sink needs to be removed, so that this doesn't need to be updated again in a month. Also, this appears to be missing the republisher.

**Comment by mikaeld** [comment]
Updated to add republishers and server-side telemetry ingestion via cloud logging

**Comment by whd** [comment]
It looks like the mmd file was deleted. What's the source file for this diagram/how does one update it?

**Comment by mikaeld** [comment]
It was made in Lucid. Licenses are available to all Mozilla employees. I can add a share link that allow Mozilla employees to access and edit the diagram. Mermaid is nice and free, but it felt like a compromise on diagram clarity.

**Review by whd — APPROVED** [review]
> I can add a share link that allow Mozilla employees to access and edit the diagram. Mermaid is nice and free, but it felt like a compromise on diagram clarity.

:+1:, I just want to make sure we don't have to rebuild this from scratch on the next update

**Review by relud — APPROVED** [review]

**Pull request merged**
